# Configuration du bouton # Configuration du bouton Sponsor - maiga-élevage

github: [boureimamaiga255-ops]
custom: ['https://taplink.biol', 'sms:+22654098813?body=Bonjour, je souhaite vous soutenir pour le projet maiga-élevage.']


